# Generated by Django 2.2.4 on 2019-08-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='아이디')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('is_logged_in', models.BooleanField(default=False, verbose_name='로그인 여부')),
                ('is_admin', models.BooleanField(default=False, verbose_name='관리자 여부')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '유저',
                'verbose_name_plural': '유저들',
                'db_table': 'user',
            },
        ),
    ]
