# Generated by Django 2.2.4 on 2019-08-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190831_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='device',
            field=models.SmallIntegerField(blank=True, choices=[(0, '데스크탑'), (1, '모바일')], null=True, verbose_name='디바이스'),
        ),
    ]
