# Generated by Django 2.2.4 on 2019-08-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='device',
            field=models.SmallIntegerField(choices=[(0, '데스크탑'), (1, '모바일')], default=0, verbose_name='디바이스'),
            preserve_default=False,
        ),
    ]
