# Generated by Django 2.2.4 on 2019-08-31 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_history_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='생성일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성화 여부'),
        ),
        migrations.AddField(
            model_name='history',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
    ]
