# Generated by Django 2.2.4 on 2019-08-31 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190831_1935'),
        ('history', '0003_auto_20190831_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='user',
        ),
        migrations.AddField(
            model_name='history',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Token', verbose_name='토큰'),
            preserve_default=False,
        ),
    ]
