# Generated by Django 2.2.4 on 2019-08-31 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_auto_20190831_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='token',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Token', verbose_name='토큰'),
        ),
    ]
