# Generated by Django 2.2.4 on 2019-08-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_auto_20190831_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='device',
            field=models.SmallIntegerField(blank=True, choices=[(0, '데스크탑'), (1, '모바일')], null=True, verbose_name='디바이스'),
        ),
    ]
