# Generated by Django 2.2.4 on 2019-08-31 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('history', '0006_auto_20190831_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='history',
            name='token',
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저'),
            preserve_default=False,
        ),
    ]
